Make configure script fancier
Test for supported warning flags before using them.
Make tests output more verbose and colorful.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,8 @@
 #!/bin/sh
 
-use_ppoll=0
 use_x11shm=1
 use_boxdrawing=1
 use_precompose=1
-use_nanosleep=0
-use_posix_shm=0
 use_clang=0
 use_uri=1
 prefix=/usr/local
@@ -15,26 +12,48 @@ cflags='-O2 -flto'
 vars=
 version=20301
 
-linkrt=' -lrt '
-
 # Test some features by trying compiling snippets
-dotest() { printf "$1" | cc -x c - $linkrt 2>&1 >/dev/null && rm -f a.out; }
+linkrt=' -lrt '
+testcc='cc'
 
 emptytest="int main(){}\n"
 shmtest="#define _POSIX_C_SOURCE 200809L\n#include <sys/mman.h>\nint main(){shm_open(0,0,0);}\n"
 ppolltest="#define _GNU_SOURCE\n#include <poll.h>\nint main(){ppoll(0,0,0,0);}\n"
 nanosleeptest="#define _POSIX_C_SOURCE 200809L\n#include <time.h>\nint main(){clock_nanosleep(0,0,0,0);}\n"
 
-if ! dotest "$emptytest"; then
-    linkrt=''
-fi
+warns="-Walloca -Wno-aggressive-loop-optimizations"
+warns="$warns -Wdisabled-optimization -Wduplicated-branches -Wduplicated-cond"
+warns="$warns -Wignored-attributes  -Wincompatible-pointer-types"
+warns="$warns -Winit-self -Wwrite-strings -Wvla"
+warns="$warns -Wmissing-attributes -Wmissing-format-attribute -Wmissing-noreturn"
+warns="$warns -Wswitch-bool -Wpacked -Wshadow -Wformat-security"
+warns="$warns -Wswitch-unreachable -Wlogical-op -Wstringop-truncation"
+warns="$warns -Wbad-function-cast -Wnested-externs -Wstrict-prototypes"
+outwarns=''
 
-# Test if system supports POSIX shared memory
-dotest "$shmtest" && use_posix_shm=1
-# Test if system supports ppoll()
-dotest "$ppolltest" && use_ppoll=1
-# Test if system supports POSIX clock_nanosleep()
-dotest "$nanosleeptest" && use_nanosleep=1
+dotest() {
+    echo -n "Testing for '$2'... " >&2
+    if printf "$1" | $testcc $linkrt -x c - >/dev/null 2>&1; then
+        rm -f a.out
+        echo "\033[1;32mYES\033[m." >&2
+        return 0
+    else
+        echo "\033[1;31mNO\033[m." >&2
+        return 1
+    fi
+}
+
+dotestwarn() {
+    echo -n "Testing for '$1' warning... " >&2
+    if printf "$emptytest" | $testcc -Werror $1 -x c - >/dev/null 2>&1; then
+        rm -f a.out
+        echo "\033[1;32mYES\033[m." >&2
+        return 0
+    else
+        echo "\033[1;31mNO\033[m." >&2
+        return 1
+    fi
+}
 
 help() {
 cat <<END
@@ -60,6 +79,7 @@ Usage: configure [options]
 END
 }
 
+oldifs="$IFS"
 IFS=''
 nl='\
 '
@@ -116,8 +136,35 @@ for i; do
     esac
 done
 
+IFS="$oldifs"
+
 if [ "$use_clang" = 1 ]; then
     vars="${vars}${nl}LDFLAGS += -fuse-ld=lld${nl}CC=clang"
+    testcc=clang
+fi
+
+if [ "$(dotest "$emptytest" "librt presence")" = 0 ]; then
+    linkrt=''
+fi
+
+# Test for presence of warning options
+for w in $warns; do
+    if dotestwarn $w; then
+        outwarns="$outwarns $w"
+    fi
+done
+
+# Test if system supports POSIX shared memory
+if [ -z $use_posix_shm ]; then
+    dotest "$shmtest" "POSIX Shared memory" && use_posix_shm=1 || use_posix_shm=0
+fi
+# Test if system supports ppoll()
+if [ -z $use_ppoll ]; then
+    dotest "$ppolltest" "ppoll() function" && use_ppoll=1 || use_ppoll=0
+fi
+# Test if system supports POSIX clock_nanosleep()
+if [ -z $use_nanosleep ]; then
+    dotest "$nanosleeptest" "clock_nanosleep() function" && use_nanosleep=1 || use_nanosleep=0
 fi
 
 vars="${vars}${nl}CFLAGS=$cflags"
@@ -169,11 +216,14 @@ sed < "./Makefile.in" > "./Makefile" \
     -e "s:@MANDIR@:$mandir:" \
     -e "s:@SHAREDIR@:$sharedir:" \
     -e "s:@DEPS@:$deps:" \
+    -e "s:@EXTRAWARNINGS@:$outwarns:" \
     -e "s:@LIBRT@:$linkrt:" \
     -e "s:@OBJECTS@:$objs:" \
     -e "s:@VARS@:$vars:"
 
 cat <<END
+
+Configure results:
     name..................... $name
     prefix................... $prefix
     bindir................... $bindir
